const {ApplicationCommandOptionType:T,CommandInteractionOptionResolver,Collection}=require('discord.js');
class PrefixError extends Error{}
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function tokenize(text){const out=[];let value='',quote=null,quoted=false,active=false;for(let n=0;n<text.length;n++){const c=text[n];if(quote){if(c===quote)quote=null;else if(c==='\\'&&text[n+1]===quote)value+=text[++n];else value+=c;active=true;}else if((c==='"'||c==="'")&&(!active||value.endsWith(':'))){quote=c;quoted=true;active=true;}else if(/\s/.test(c)){if(active)out.push({value,quoted});value='';quoted=false;active=false;}else{value+=c;active=true;}}if(quote)throw new PrefixError('Guillemet non fermé.');if(active)out.push({value,quoted});return out;}
function layout(schema,tokens){const branch=[];let defs=schema.options||[];while(defs.some(o=>[T.Subcommand,T.SubcommandGroup].includes(o.type))){const name=tokens.shift()?.value,choice=defs.find(o=>o.name===normalize(name));if(!choice)throw new PrefixError(`Choisis une sous-commande : ${defs.map(o=>o.name).join(', ')}.`);branch.push(choice);defs=choice.options||[];}return{branch,defs};}
function wrap(data,branch){for(const b of [...branch].reverse())data=[{name:b.name,type:b.type,options:data}];return data;}
function splitArgs(defs,tokens){const named=new Map(),pos=[];const match=t=>{const m=/^([a-z0-9_-]+):(.*)$/i.exec(t.value);return m&&defs.some(d=>d.name===m[1])?m:null;};for(let n=0;n<tokens.length;n++){const m=match(tokens[n]);if(!m){pos.push(tokens[n]);continue;}if(named.has(m[1]))throw new PrefixError(`Option répétée : ${m[1]}.`);const parts=m[2]?[m[2]]:[];while(n+1<tokens.length&&!match(tokens[n+1]))parts.push(tokens[++n].value);named.set(m[1],parts.join(' '));}const values=new Map(named);for(let n=0;n<defs.length;n++){const d=defs[n];if(values.has(d.name)||!pos.length)continue;const p=pos.shift();let value=p.value;if(d.type===T.String&&!d.choices&&!d.autocomplete&&!p.quoted&&defs.slice(n+1).every(x=>!x.required||named.has(x.name))){value=[value,...pos.splice(0).map(t=>t.value)].join(' ');}values.set(d.name,value);}if(pos.length)throw new PrefixError('Trop d’arguments. Consulte =aide pour la syntaxe.');return values;}
function entityId(value){return /^(?:<[@#]!?|<@&)?(\d{17,20})>?$/.exec(value)?.[1]||null;}
async function convert(def,raw,context){const {guild,client}=context;let value=raw;
 if(def.choices){const choice=def.choices.find(c=>normalize(c.value)===normalize(raw)||normalize(c.name)===normalize(raw));if(!choice)throw new PrefixError(`${def.name} : choisis ${def.choices.map(c=>c.value).join(', ')}.`);value=choice.value;}
 const option={name:def.name,type:def.type,value};
 if([T.User,T.Channel,T.Role,T.Mentionable].includes(def.type)){
  let id=entityId(raw),entity;
  if(def.type===T.Channel){entity=id?(guild.channels.cache.get(id)||await guild.channels.fetch(id).catch(()=>null)):guild.channels.cache.find(c=>normalize(c.name)===normalize(raw));if(!entity||entity.guildId!==guild.id||def.channel_types&&!def.channel_types.includes(entity.type))throw new PrefixError(`${def.name} : salon introuvable ou de type incorrect.`);option.channel=entity;}
  else if(def.type===T.Role||(def.type===T.Mentionable&&(raw.startsWith('<@&')||guild.roles.cache.has(id)))){entity=id?(guild.roles.cache.get(id)||await guild.roles.fetch(id).catch(()=>null)):guild.roles.cache.find(r=>normalize(r.name)===normalize(raw));if(!entity)throw new PrefixError(`${def.name} : rôle introuvable.`);option.role=entity;}
  else{if(!id){const found=guild.members.cache.filter(m=>[m.displayName,m.user.username,m.user.globalName,m.user.tag].some(v=>v&&normalize(v)===normalize(raw)));if(found.size!==1)throw new PrefixError(`${def.name} : utilise une mention ou l’ID Discord du membre.`);id=found.first().id;}entity=client.users.cache.get(id)||await client.users.fetch(id).catch(()=>null);if(!entity)throw new PrefixError(`${def.name} : utilisateur introuvable.`);option.user=entity;option.member=guild.members.cache.get(id)||null;}
  option.value=entity.id;
 }else if(def.type===T.Boolean){if(['oui','true','on','1'].includes(normalize(value)))option.value=true;else if(['non','false','off','0'].includes(normalize(value)))option.value=false;else throw new PrefixError(`${def.name} : indique oui ou non.`);}
 else if([T.Integer,T.Number].includes(def.type)){option.value=Number(value);if(!Number.isFinite(option.value)||(def.type===T.Integer&&!Number.isSafeInteger(option.value))||(def.min_value!==undefined&&option.value<def.min_value)||(def.max_value!==undefined&&option.value>def.max_value))throw new PrefixError(`${def.name} : nombre invalide ou hors limites.`);}
 else if(def.type===T.String){option.value=String(value);if(option.value.length<(def.min_length||0)||option.value.length>(def.max_length||6000))throw new PrefixError(`${def.name} : longueur incorrecte.`);}
 else if(def.type===T.Attachment){const attachment=context.attachments?.find(a=>a.id===raw||a.name===raw)||context.attachments?.first();if(!attachment)throw new PrefixError(`${def.name} : joins le fichier au message.`);option.attachment=attachment;option.value=attachment.id;}
 return option;
}
async function parse(command,text,context){const schema=command.data.toJSON(),tokens=tokenize(text),{defs,branch}=layout(schema,tokens),values=splitArgs(defs,tokens),flat=[];
 for(const def of defs){if(!values.has(def.name)){if(def.required)throw new PrefixError(`Option obligatoire : ${def.name}. Consulte =aide ${schema.name}.`);continue;}flat.push(await convert(def,values.get(def.name),context));}
 for(const def of defs.filter(d=>d.autocomplete&&values.has(d.name))){if(!command.autocomplete)continue;const item=flat.find(o=>o.name===def.name);let candidates=[];const resolver=new CommandInteractionOptionResolver(context.client,wrap(flat,branch));resolver.getFocused=full=>full?{name:def.name,value:item.value}:item.value;await command.autocomplete({...context,commandName:schema.name,options:resolver,isAutocomplete:()=>true,respond:async choices=>{candidates=choices;}});const exact=candidates.find(c=>normalize(c.value)===normalize(item.value)||normalize(c.name)===normalize(item.value));const partial=candidates.filter(c=>normalize(c.name).includes(normalize(item.value)));const selected=exact||(partial.length===1?partial[0]:null);if(selected)item.value=selected.value;else if(candidates.length>1)throw new PrefixError(`${def.name} : plusieurs choix possibles : ${candidates.slice(0,10).map(c=>c.name).join(' ; ')}.`);}
 return wrap(flat,branch);
}
function resolver(client,data){const resolved={users:new Collection(),members:new Collection(),roles:new Collection(),channels:new Collection(),attachments:new Collection()};function visit(items){for(const o of items){if(o.options)visit(o.options);for(const [key,map]of [['user','users'],['member','members'],['role','roles'],['channel','channels'],['attachment','attachments']])if(o[key])resolved[map].set(o.value,o[key]);}}visit(data);return new CommandInteractionOptionResolver(client,data,resolved);}
function usages(schema){const lines=[];function branch(prefix,defs){const children=defs.filter(d=>[T.Subcommand,T.SubcommandGroup].includes(d.type));if(children.length){for(const child of children)branch(prefix+' '+child.name,child.options||[]);return;}lines.push(prefix+' '+defs.map(d=>d.required?`<${d.name}>`:`[${d.name}]`).join(' '));for(const d of defs)lines.push(`${d.name} : ${d.description}${d.choices?' — '+d.choices.map(c=>`${c.name} (${c.value})`).join(', '):''}`);}branch('='+schema.name,schema.options||[]);return lines.join('\n');}
module.exports={PrefixError,normalize,tokenize,layout,splitArgs,convert,parse,resolver,usages};
