const {SlashCommandBuilder,EmbedBuilder,MessageFlags}=require('discord.js');const {allowed}=require('../utils/memberCare');const {COLORS,ROLES}=require('../config/soulSociety');const {read}=require('../utils/recruitmentData');const {duration}=require('../utils/soulActivityHelpers');
module.exports={data:new SlashCommandBuilder().setName('suivi-test').setDescription('Consulter le suivi de la période de test d’un membre').addUserOption(o=>o.setName('membre').setDescription('Membre à consulter').setRequired(true)),
async execute(i){if(!allowed(i,true))return i.reply({content:'❌ Accès réservé au recrutement et à la direction.',flags:MessageFlags.Ephemeral});await i.deferReply({flags:MessageFlags.Ephemeral});
try{const user=i.options.getUser('membre',true),member=await i.guild.members.fetch(user.id).catch(()=>null);if(!member||user.bot)return i.editReply('❌ Membre introuvable.');
const test=require('../utils/candidateArchive').testPeriod(user.id,read('candidateArchive'),member.roles.cache.has(ROLES.test),read('memberTests')[user.id]),app=read('candidatures')[user.id],profile=read('welcomeProfiles')[user.id];const active=member.roles.cache.has(ROLES.test);const start=active&&!test?.endedAt?test?.startedAt:null;const days=start?Math.floor((Date.now()-start)/86400000):null;
const e=new EmbedBuilder().setColor(COLORS.primary).setTitle('🧪 Suivi de test • La Soul Society').setDescription(`<@${user.id}>\n**Statut :** ${active?'Membre Test':'Ne possède pas actuellement le rôle Membre Test'}`)
.addFields({name:'Début de la période actuelle',value:start?`<t:${Math.floor(start/1000)}:f> — ${days} jour(s)`:'Date non établie par les logs disponibles ; import historique en cours ou source absente.'},
{name:'Repère de durée',value:active?'1 à 2 semaines selon l’activité. La décision de validation reste à la gestion.':'Aucune période de test active reconnue.'},
{name:'Parcours =bienvenue',value:profile?.completedAt||profile?.step==='done'?'✅ Terminé':'⏳ Non terminé'},
{name:'Candidature / entretien',value:app?.reviewMessageId&&app?.reviewChannelId?`[Consulter la candidature](https://discord.com/channels/${i.guildId}/${app.reviewChannelId}/${app.reviewMessageId})\nComptes-rendus : <#1550241655255203921>`:'Candidature non retrouvée. Comptes-rendus : <#1550241655255203921>'});
if(test?.source)e.addFields({name:'Source du début de test',value:`[Consulter le message](${test.source})${test.evidence==='announcement'?' — date de publication de l’annonce, attribution exacte non garantie.':''}`});
if(start&&i.client.soulActivity){i.client.soulActivity.sync(member);const ledger=i.client.soulActivity.ledger;const from=Math.max(start,ledger.data.since,Date.now()-32*86400000);const stats=ledger.totals(user.id,from);e.addFields({name:'Activité pendant le test',value:`💬 ${stats.messages} messages\n🎙️ ${duration(stats.voiceMs)}${from>start?'\n⚠️ Historique partiel depuis le début du suivi disponible.':''}`});}
const absences=Object.values(read('memberAbsences')).filter(a=>a.guildId===i.guildId&&a.userId===user.id&&a.end+86400000>Date.now());e.addFields({name:'Absences en cours ou prévues',value:absences.length?absences.slice(-5).map(a=>`<t:${Math.floor(a.start/1000)}:d> → <t:${Math.floor(a.end/1000)}:d>`).join('\n'):'Aucune absence enregistrée.'});return i.editReply({embeds:[e],allowedMentions:{parse:[]}});
}catch{return i.editReply('❌ Impossible de consulter le suivi pour le moment.');}}
};
